/**
 * CSS Generation Script
 *
 * Converts design tokens from tokens.config.ts into CSS custom properties
 * and Tailwind CSS v4 compatible utilities.
 *
 * Usage:
 * - Run automatically during build: `pnpm build`
 * - Run manually: `ts-node src/design-system/generateCSS.ts`
 *
 * Output: src/app/design-system-generated.css
 */

import { tokens, type ColorScale } from './tokens.config';
import { writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Generate CSS custom properties from color scale
 */
function generateColorProperties(name: string, scale: ColorScale): string {
  return Object.entries(scale)
    .map(([key, value]) => `  --color-${name}-${key}: ${value};`)
    .join('\n');
}

/**
 * Generate all CSS custom properties
 */
function generateCSSProperties(): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated Design System Tokens',
    ' * Generated from: src/design-system/tokens.config.ts',
    ' * Do not edit this file directly - edit tokens.config.ts instead',
    ' */',
    '',
    ':root {',
    '  /* ===== Colors ===== */',
    '',
    '  /* Primary (Sapphire) */',
    generateColorProperties('primary', tokens.colors.primary),
    '',
    '  /* Secondary (Amethyst) */',
    generateColorProperties('secondary', tokens.colors.secondary),
    '',
    '  /* Accent (Emerald) */',
    generateColorProperties('accent', tokens.colors.accent),
    '',
    '  /* Neutral (Grays) */',
    generateColorProperties('neutral', tokens.colors.neutral),
    '',
    '  /* Extended Palettes */',
    generateColorProperties('emerald', tokens.colors.emerald),
    generateColorProperties('sapphire', tokens.colors.sapphire),
    generateColorProperties('ruby', tokens.colors.ruby),
    generateColorProperties('amethyst', tokens.colors.amethyst),
    '',
    '  /* ===== Spacing ===== */',
    ...Object.entries(tokens.spacing).map(
      ([key, value]) => `  --spacing-${key}: ${value};`
    ),
    '',
    '  /* ===== Typography ===== */',
    '',
    '  /* Font Families */',
    ...Object.entries(tokens.typography.fontFamily).map(
      ([key, value]) => `  --font-${key}: ${value};`
    ),
    '',
    '  /* Font Sizes */',
    ...Object.entries(tokens.typography.fontSize).map(
      ([key, value]) => `  --text-${key}: ${value};`
    ),
    '',
    '  /* Font Weights */',
    ...Object.entries(tokens.typography.fontWeight).map(
      ([key, value]) => `  --font-weight-${key}: ${value};`
    ),
    '',
    '  /* Line Heights */',
    ...Object.entries(tokens.typography.lineHeight).map(
      ([key, value]) => `  --leading-${key}: ${value};`
    ),
    '',
    '  /* ===== Border Radius ===== */',
    ...Object.entries(tokens.borderRadius).map(([key, value]) =>
      key === 'DEFAULT'
        ? `  --rounded: ${value};`
        : `  --rounded-${key}: ${value};`
    ),
    '',
    '  /* ===== Shadows ===== */',
    ...Object.entries(tokens.shadows).map(
      ([key, value]) => `  --shadow-${key}: ${value};`
    ),
    '',
    '  /* ===== Animation ===== */',
    '',
    '  /* Easing Functions */',
    ...Object.entries(tokens.animation.easing).map(
      ([key, value]) => `  --ease-${key}: cubic-bezier(${value.join(', ')});`
    ),
    '',
    '  /* Durations */',
    ...Object.entries(tokens.animation.duration).map(
      ([key, value]) => `  --duration-${key}: ${value}ms;`
    ),
    '',
    '  /* ===== Glass Effects ===== */',
    '',
    '  /* Glass SM */',
    `  --glass-sm-bg: ${tokens.glass.sm.background};`,
    `  --glass-sm-blur: ${tokens.glass.sm.blur};`,
    `  --glass-sm-border: ${tokens.glass.sm.border};`,
    `  --glass-sm-shadow: ${tokens.glass.sm.shadow};`,
    '',
    '  /* Glass MD */',
    `  --glass-md-bg: ${tokens.glass.md.background};`,
    `  --glass-md-blur: ${tokens.glass.md.blur};`,
    `  --glass-md-border: ${tokens.glass.md.border};`,
    `  --glass-md-shadow: ${tokens.glass.md.shadow};`,
    '',
    '  /* Glass LG */',
    `  --glass-lg-bg: ${tokens.glass.lg.background};`,
    `  --glass-lg-blur: ${tokens.glass.lg.blur};`,
    `  --glass-lg-border: ${tokens.glass.lg.border};`,
    `  --glass-lg-shadow: ${tokens.glass.lg.shadow};`,
    '',
    '  /* Glass Card */',
    `  --glass-card-bg: ${tokens.glass.card.background};`,
    `  --glass-card-blur: ${tokens.glass.card.blur};`,
    `  --glass-card-border: ${tokens.glass.card.border};`,
    `  --glass-card-shadow: ${tokens.glass.card.shadow};`,
    '',
    '  /* ===== Backgrounds ===== */',
    ...Object.entries(tokens.background).map(
      ([key, value]) => `  --bg-${key}: ${value};`
    ),
    '}',
  ];

  return lines.join('\n');
}

/**
 * Generate utility classes using CSS custom properties
 */
function generateUtilityClasses(): string {
  return `
/* ===== Utility Classes ===== */

/* Glass Effect Utilities */
.glass-sm {
  background: var(--glass-sm-bg);
  backdrop-filter: blur(var(--glass-sm-blur));
  -webkit-backdrop-filter: blur(var(--glass-sm-blur));
  border: 1px solid var(--glass-sm-border);
  box-shadow: var(--glass-sm-shadow);
}

.glass,
.glass-md {
  background: var(--glass-md-bg);
  backdrop-filter: blur(var(--glass-md-blur));
  -webkit-backdrop-filter: blur(var(--glass-md-blur));
  border: 1px solid var(--glass-md-border);
  box-shadow: var(--glass-md-shadow);
}

.glass-lg {
  background: var(--glass-lg-bg);
  backdrop-filter: blur(var(--glass-lg-blur));
  -webkit-backdrop-filter: blur(var(--glass-lg-blur));
  border: 1px solid var(--glass-lg-border);
  box-shadow: var(--glass-lg-shadow);
}

.glass-card {
  background: var(--glass-card-bg);
  backdrop-filter: blur(var(--glass-card-blur));
  -webkit-backdrop-filter: blur(var(--glass-card-blur));
  border: 1px solid var(--glass-card-border);
  box-shadow: var(--glass-card-shadow);
  transition: all 0.3s ease;
}

.glass-card:hover {
  border: 1px solid rgba(147, 51, 234, 0.22);
  box-shadow: 0 12px 48px 0 rgba(30, 58, 138, 0.3), 0 0 32px rgba(147, 51, 234, 0.15);
  transform: translateY(-2px);
}

/* Gradient Text */
.gradient-text {
  background: linear-gradient(135deg, #60a5fa 0%, #a78bfa 50%, #c084fc 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
}

/* Hero Gradient Background */
.hero-gradient {
  background: linear-gradient(
    135deg,
    rgba(37, 99, 235, 0.3) 0%,
    rgba(147, 51, 234, 0.3) 50%,
    rgba(37, 99, 235, 0.3) 100%
  );
}

/* Button Utilities */
.btn-primary {
  background: linear-gradient(135deg, var(--color-primary-600) 0%, var(--color-secondary-600) 100%);
  color: white;
  padding: 0.75rem 2rem;
  border-radius: var(--rounded-lg);
  font-weight: var(--font-weight-semibold);
  transition: all var(--duration-normal) ease;
  border: 1px solid rgba(147, 51, 234, 0.3);
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 24px rgba(37, 99, 235, 0.4), 0 0 20px rgba(147, 51, 234, 0.3);
}

.btn-secondary {
  background: rgba(255, 255, 255, 0.05);
  backdrop-filter: blur(10px);
  color: white;
  padding: 0.75rem 2rem;
  border-radius: var(--rounded-lg);
  font-weight: var(--font-weight-semibold);
  transition: all var(--duration-normal) ease;
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.btn-secondary:hover {
  background: rgba(255, 255, 255, 0.1);
  transform: translateY(-2px);
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
}

/* Section Container */
.section-container {
  max-width: 1280px;
  margin: 0 auto;
  padding: 4rem 1rem;
}

@media (min-width: 768px) {
  .section-container {
    padding: 5rem 2rem;
  }
}

/* Text Shadow Utility */
.text-shadow {
  text-shadow: 1px 2px 2px var(--color-primary-600);
}

/* Font Family Utilities */
.font-playfair {
  font-family: var(--font-playfair);
}

.font-ephesis {
  font-family: var(--font-ephesis);
}
`;
}

/**
 * Main generation function
 */
function generate() {
  const cssProperties = generateCSSProperties();
  const utilityClasses = generateUtilityClasses();

  const fullCSS = cssProperties + '\n' + utilityClasses;

  const outputPath = join(process.cwd(), 'src', 'app', 'design-system-generated.css');

  writeFileSync(outputPath, fullCSS, 'utf-8');

  console.log('✅ Design system CSS generated successfully!');
  console.log(`📁 Output: ${outputPath}`);
  console.log(`📊 Generated ${fullCSS.split('\n').length} lines of CSS`);
}

// Run if executed directly
if (require.main === module) {
  generate();
}

export { generate };
